runtime:
  cache_dir: ./.cache/antora

site:
  title: OpenShift Pipelines
  url: https://joaedwar.github.io/pipelines-tutorial/docs
  start_page: docs::index.adoc  
content:
  sources:
    - url: https://joaedwar.github.io/pipelines-tutorial/docs.git 
      branches: master     
ui:
  bundle:
    url: https://joaedwar.github.io/pipelines-tutorial/blob/master/ui-bundle.zip
 
