= Installing the OpenShift Pipelines Operator

OpenShift Pipelines can be installed by using an operator that is available in the OpenShift OperatorHub.



.Prerequisites

* An OpenShift 4 cluster is required for installation. Visit try.openshift.com for information on setting up an OpenShift 4 cluster.


== Creating a Knative Serving Operator Subscription

.Procedure

. In the Web Console, navigate to **Home > Projects** . 

. Click **Create Project**.  A dialog box will appear.

. Enter 'pipelines` in the name field and click **Create**.

. Go to **Catalog > OperatorHub** in the Web Console. A list of operators for OpenShift is provided.

. Click on the **OpenShift Pipelines Operator** tile. 
---
+
NOTE: Use the **Filter by Keyword** box to facilitate the search of the Knative Serving operator in the catalog.  

. A `Show Community Operator` dialog box will appear. Click **Continue** to proceed.

. The **OpenShift Pipelines Operator** descriptor screen will appear. Click **Install**.

. On the **Create the Operator Subscription** screen, go to the **Installation Mode** section and choose **A specific namespace on the cluster**.

. Ensure the `pipelines` namespace is selected. Click **Subscribe**.
---
+
NOTE: Selecting the default values will install the operator in all namespaces.
 
. Confirm the subscription for the installation operator, by viewing the **Subscription Overview**. Observe as the **UPGRADE STATUS** goes for `1 installing` to `1 installed`.


== Installing the OpenShift Pipelines Operator

. Click the `1 installed` link.

. Click  **Create New** to install the `OpenShift Pipelines` Custom Resources (CR). 

. The **Create OpenShift Pipelines** editor screen will appear. Click **Create** to set the values.
---
+
NOTE:  The editor is pre-populated with definitions. Configure the file by manually entering YAML or JSON definitions, or by dragging and dropping a file into the editor.

. OpenShift pipelines is now installed. Check on OpenShift Pipleins installation and operation by navigating to **Workloads > Pods**  and selecting the **Logs** tab.
