apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build-app
    taskRef:
      name: maven-build
    resources:
      inputs:
      - name: workspace-git
        resource: app-git
      outputs:
      - name: workspace-git
        resource: app-git
  - name: s2i-gen-dockerfile
    taskRef:
      name: s2i
    resources:
      inputs:
      - name: workspace-git
        resource: app-git
        from: [build-app]
      outputs:
      - name: workspace-git
        resource: app-git
  - name: build-image
    taskRef:
      name: buildah
    params:
    - name: dockerfile
      value: Dockerfile
    - name: verifyTLS
      value: "false"
    resources:
      inputs:
      - name: workspace-git
        resource: mapit-git
        from: [s2i-gen-dockerfile]
      outputs:
      - name: image
        resource: mapit-image
  - name: deploy
    taskRef:
      name: openshift-cli
    runAfter:
      - build-image
    params:
    - name: command
      value: "rollout latest spring-petclinic"
